### ISSUE TITLE
Add your repo initiating cmds to start binary file means ?.cannot understand bro

### ISSUE THREAD

**Issue by shiva20991** [rahulkhatri137/heroku-bypass#1]

**Comment by rahulkhatri137** [comment]
Go through the repo & find start cmd either from dockerfile or there should be a start script!

**Comment by shiva20991** [comment]
Bro thier is start.sh .we want to upload that file to this repo ?..they start.sh in docker also ..

**Comment by rahulkhatri137** [comment]
Yes u need to copy stuff inside start.sh

**Comment by shiva20991** [comment]
Thanks bro ..i will try this pin a result bro
