### ISSUE TITLE
bro thier is no module bash start 

### ISSUE THREAD

**Issue by shiva20991** [rahulkhatri137/heroku-bypass#2]
![image](https://user-images.githubusercontent.com/80451254/168751133-15de4192-6daa-4359-bedc-d41eb24af485.png)

 github repo link - https://github.com/shiva20991/test-bypass

i have added all things

**Comment by rahulkhatri137** [comment]
Then change cmd in Dockerfile from "bash", "start" to "python3", "-m", "bot"
